### PR TITLE
PoissonRegressor UT

### PR DESCRIPTION
**Pull request by vikash018**
PoissonRegressor UT

### CODE REVIEW

**Review by oualib — APPROVED** [review]

**Comment by oualib** [comment]
Excellent: do you check for linear model if we get the same coefficients?

**Comment by vikash018** [comment]
Yes. Our coefficients are matching with sklearn. Only we need to set very low value of alpha (Constant that multiplies the L2 penalty term).
PoissonRegressor(alpha=0.00005, tol=1e-06)

**Comment by oualib** [comment]
@vikash018 is it part of linear models tests?

**Comment by vikash018** [comment]
yes.

**Pull request merged**
