### PR TITLE
778 tests vdataframe machine learning + join union sort + pivot

### PR DESCRIPTION
**Pull request by vikash018**
UT for machine learning, join union sort  and pivot files.

### CODE REVIEW

**Comment by oualib** [comment]
why 300 tests are failing?

**Review by oualib — COMMENTED** [review]
@mail4umar please look carefully at this PR and share with Vikash your feedback

**Comment by vikash018** [comment]
> why 300 tests are failing?

@oualib - I checked logs and looks like plotting related tests are failing.
@mail4umar - could you pls have a look at plotting test? 

verticapy/tests_new/mlops/test_model_versioning.py .....                 [ 75%]
verticapy/tests_new/plotting/highcharts/test_highcharts_acf.py F.F..FF   [ 75%]
verticapy/tests_new/plotting/highcharts/test_highcharts_bar.py F....FFFF [ 75%]
FF....FFFF                                                               [ 75%]
verticapy/tests_new/plotting/highcharts/test_highcharts_barh.py FFF..FFF [ 76%]
FFFFFF..FF                                                               [ 76%]
verticapy/tests_new/plotting/highcharts/test_highcharts_boxplot.py FF..s [ 76%]
F..ssF..sF                                                               [ 76%]
verticapy/tests_new/plotting/highcharts/test_highcharts_candlestick.py . [ 76%]
ssFFFFs                                                                  [ 76%]
verticapy/tests_new/plotting/highcharts/test_highcharts_contour.py F.... [ 77%]
FF                                                                       [ 77%]
verticapy/tests_new/plotting/highcharts/test_highcharts_density.py F.... [ 77%]
FFFF....F....FFF                                                         [ 77%]
verticapy/tests_new/plotting/highcharts/test_highcharts_heatmap.py F.... [ 77%]
FFsssssss                                                                [ 78%]
verticapy/tests_new/plotting/highcharts/test_highcharts_hist.py F...FF.F [ 78%]
...ss.                                                                   [ 78%]
verticapy/tests_new/plotting/highcharts/test_highcharts_line.py F...sFFF [ 78%]
FFF.F..                                                                  [ 78%]
verticapy/tests_new/plotting/highcharts/test_highcharts_outliers.py F... [ 78%]
.FF....                                                                  [ 79%]
verticapy/tests_new/plotting/highcharts/test_highcharts_pie.py FFFFFF    [ 79%]
verticapy/tests_new/plotting/highcharts/test_highcharts_range.py F....FF [ 79%]
F....FF                                                                  [ 79%]
verticapy/tests_new/plotting/highcharts/test_highcharts_scatter.py F.... [ 79%]
FFFFF....FF                                                              [ 79%]
verticapy/tests_new/plotting/highcharts/test_highcharts_spider.py FFF    [ 80%]
verticapy/tests_new/plotting/highcharts/machine_learning/test_highcharts_champion_challenger.py F [ 80%]
                                                                         [ 80%]

**Comment by oualib** [comment]
> > why 300 tests are failing?
> 
> @oualib - I checked logs and looks like plotting related tests are failing. @mail4umar - could you pls have a look at plotting test?
> 
> verticapy/tests_new/mlops/test_model_versioning.py ..... [ 75%] verticapy/tests_new/plotting/highcharts/test_highcharts_acf.py F.F..FF [ 75%] verticapy/tests_new/plotting/highcharts/test_highcharts_bar.py F....FFFF [ 75%] FF....FFFF [ 75%] verticapy/tests_new/plotting/highcharts/test_highcharts_barh.py FFF..FFF [ 76%] FFFFFF..FF [ 76%] verticapy/tests_new/plotting/highcharts/test_highcharts_boxplot.py FF..s [ 76%] F..ssF..sF [ 76%] verticapy/tests_new/plotting/highcharts/test_highcharts_candlestick.py . [ 76%] ssFFFFs [ 76%] verticapy/tests_new/plotting/highcharts/test_highcharts_contour.py F.... [ 77%] FF [ 77%] verticapy/tests_new/plotting/highcharts/test_highcharts_density.py F.... [ 77%] FFFF....F....FFF [ 77%] verticapy/tests_new/plotting/highcharts/test_highcharts_heatmap.py F.... [ 77%] FFsssssss [ 78%] verticapy/tests_new/plotting/highcharts/test_highcharts_hist.py F...FF.F [ 78%] ...ss. [ 78%] verticapy/tests_new/plotting/highcharts/test_highcharts_line.py F...sFFF [ 78%] FFF.F.. [ 78%] verticapy/tests_new/plotting/highcharts/test_highcharts_outliers.py F... [ 78%] .FF.... [ 79%] verticapy/tests_new/plotting/highcharts/test_highcharts_pie.py FFFFFF [ 79%] verticapy/tests_new/plotting/highcharts/test_highcharts_range.py F....FF [ 79%] F....FF [ 79%] verticapy/tests_new/plotting/highcharts/test_highcharts_scatter.py F.... [ 79%] FFFFF....FF [ 79%] verticapy/tests_new/plotting/highcharts/test_highcharts_spider.py FFF [ 80%] verticapy/tests_new/plotting/highcharts/machine_learning/test_highcharts_champion_challenger.py F [ 80%] [ 80%]

@vikash018  I don't think it has something specifically to do with plotting test but the test structure. I think the plotting library was maybe changed during the tests leading to wrong object creation. Idk how is it possible with your PR. Maybe because of an import. Please avoid the "import *".

**Comment by vikash018** [comment]
> > > why 300 tests are failing?
> > 
> > 
> > @oualib - I checked logs and looks like plotting related tests are failing. @mail4umar - could you pls have a look at plotting test?
> > verticapy/tests_new/mlops/test_model_versioning.py ..... [ 75%] verticapy/tests_new/plotting/highcharts/test_highcharts_acf.py F.F..FF [ 75%] verticapy/tests_new/plotting/highcharts/test_highcharts_bar.py F....FFFF [ 75%] FF....FFFF [ 75%] verticapy/tests_new/plotting/highcharts/test_highcharts_barh.py FFF..FFF [ 76%] FFFFFF..FF [ 76%] verticapy/tests_new/plotting/highcharts/test_highcharts_boxplot.py FF..s [ 76%] F..ssF..sF [ 76%] verticapy/tests_new/plotting/highcharts/test_highcharts_candlestick.py . [ 76%] ssFFFFs [ 76%] verticapy/tests_new/plotting/highcharts/test_highcharts_contour.py F.... [ 77%] FF [ 77%] verticapy/tests_new/plotting/highcharts/test_highcharts_density.py F.... [ 77%] FFFF....F....FFF [ 77%] verticapy/tests_new/plotting/highcharts/test_highcharts_heatmap.py F.... [ 77%] FFsssssss [ 78%] verticapy/tests_new/plotting/highcharts/test_highcharts_hist.py F...FF.F [ 78%] ...ss. [ 78%] verticapy/tests_new/plotting/highcharts/test_highcharts_line.py F...sFFF [ 78%] FFF.F.. [ 78%] verticapy/tests_new/plotting/highcharts/test_highcharts_outliers.py F... [ 78%] .FF.... [ 79%] verticapy/tests_new/plotting/highcharts/test_highcharts_pie.py FFFFFF [ 79%] verticapy/tests_new/plotting/highcharts/test_highcharts_range.py F....FF [ 79%] F....FF [ 79%] verticapy/tests_new/plotting/highcharts/test_highcharts_scatter.py F.... [ 79%] FFFFF....FF [ 79%] verticapy/tests_new/plotting/highcharts/test_highcharts_spider.py FFF [ 80%] verticapy/tests_new/plotting/highcharts/machine_learning/test_highcharts_champion_challenger.py F [ 80%] [ 80%]
> 
> @vikash018 I don't think it has something specifically to do with plotting test but the test structure. I think the plotting library was maybe changed during the tests leading to wrong object creation. Idk how is it possible with your PR. Maybe because of an import. Please avoid the "import *".

@oualib - oh i see. I was doing one import in master conftest file. Now, I have moved this conftest import to test_machine_learning.py to avoid import at master conftest level. Hopefully this should resolve issue.

**Review by oualib — APPROVED** [review]

**Pull request merged**
