### PR TITLE
863 unit testing model importexport

### PR DESCRIPTION
**Pull request by vikash018**
This UT covers model import/export for following models.
RandomForestRegressor,
RandomForestClassifier,
DecisionTreeRegressor,
DecisionTreeClassifier,
DummyTreeRegressor,
XGBRegressor,
XGBClassifier,
Ridge,
Lasso,
ElasticNet,
LinearRegression,
LinearSVR,
PoissonRegressor,
AR,
MA,
ARMA,
ARIMA,

### CODE REVIEW

**Review by oualib — CHANGES_REQUESTED** [review]
Everything looks good but:
1. Please create a folder named tensorflow and inside create a utils folder and move the freeze script inside. verticapy -> machine_learning -> vertica -> tensorflow -> [__init__.py (import inside TensorFlow model from base), base.py (it corresponds to the current tensorflow file), freeze_tf2_model.py]
2. Skip the TF test when we work with Python 3.12 with as error message that heras is not supported by keras.

**Review by oualib — APPROVED** [review]

**Comment by oualib** [comment]
@vikash018 I've corrected many points but still the tests are not passing.
TODO:
1. Do not install tensorflow for py312 (try to change the script and the requirements for that)
2. Try to solve the errors with your tests (look at the Py311 kernel).

**Comment by vikash018** [comment]
> @vikash018 I've corrected many points but still the tests are not passing. TODO:
> 
> 1. Do not install tensorflow for py312 (try to change the script and the requirements for that)
> 2. Try to solve the errors with your tests (look at the Py311 kernel).

@oualib - Thanks for fixing it. for model export, i am trying to create export model inside /tmp/ folder. do we need to have some extra permission?
 
Cannot create directory: [/tmp/test_fKzm/vpy_model/]
 
"SELECT EXPORT_MODELS('/tmp/test_fKzm', 'test_fKzm.vpy_model')"

**Comment by oualib** [comment]
> > @vikash018 I've corrected many points but still the tests are not passing. TODO:
> > 
> > 1. Do not install tensorflow for py312 (try to change the script and the requirements for that)
> > 2. Try to solve the errors with your tests (look at the Py311 kernel).
> 
> @oualib - Thanks for fixing it. for model export, i am trying to create export model inside /tmp/ folder. do we need to have some extra permission?
> 
> Cannot create directory: [/tmp/test_fKzm/vpy_model/]
> 
> "SELECT EXPORT_MODELS('/tmp/test_fKzm', 'test_fKzm.vpy_model')"

@afard please help @vikash018 asap we need to fix this today

**Pull request merged**
